### ISSUE TITLE
Generated typescript has no reference to deprecated service messages

### ISSUE THREAD

**Issue by zerovox** [palantir/conjure-typescript#120]
## What happened?
I marked some fields with a deprecation message in a service api:
```
      getGraph:
        deprecated: since 2.0
        returns: GetGraphResponse
        ...
```
It generated the following typing:
```
getGraph(graphRid: string): Promise<IGetGraphResponse>;
```

## What did you want to happen?
I expected this deprecation message to appear somewhere in the generated typescript, probably utilizing [JSDoc deprecated annotation](https://jsdoc.app/tags-deprecated.html) which is supported by all good IDEs:
```
/**
 * @deprecated since 2.0
 */ 
getGraph(graphRid: string): Promise<IGetGraphResponse>;
```
