### ISSUE TITLE
Conjure doesn't escape argument names in TypeScript APIs

### ISSUE THREAD

**Issue by eduardische** [palantir/conjure-typescript#129]
## What happened?

I defined the following endpoint in Conjure:
```
testTypeScript:
  http: GET /test
  args:
    function:
      type: string
      param-id: Function
      param-type: header
  returns: string
```

The API works, but when trying to generate TypeScript for this API, it fails to compile it with the following two lines using `function` as parameter name at fault:

```
testTypeScript(function: string): Promise<string>;
...
public testTypeScript(function: string): Promise<string> {
```

I depend on 4.0.0:
```
com.palantir.conjure.typescript:conjure-typescript = 4.0.0
```

## What did you want to happen?

Parameter name should be escaped or prefixed, since it's a reserved keyword in TypeScript.
