### ISSUE TITLE
Enum keys in map are not optional

### ISSUE THREAD

**Issue by tzyl** [palantir/conjure-typescript#52]
With the following example object definitions:

```
types:
  definitions:
    objects:
      Job:
        values:
          - CHEF
          - MUSICIAN
          - TEACHER
      Salaries:
        alias: map<Job, double>
      SalaryResponse:
        fields:
          salaries: Salaries
```

The generated Java object can use none/some/all of the enum values as keys in the underlying map:

```
private final Map<Job, Double> value;
```

But the generated typescript interface requires all the keys to be present:

```
import { Job } from "./job";

export interface ISalaryResponse {
    'salaries': { [key in Job]: number | "NaN" };
}
```
![conjure-enum-as-key](https://user-images.githubusercontent.com/13809355/44403112-7fcbe800-a54b-11e8-842b-eeaa60b876e8.png)

The `[key in Job]` properties should be optional to match the Java behaviour.
